target 'GJCARDRIVER' do
platform :ios, '7.0'
pod 'BaiduMapKit', '~> 2.9.1'
pod 'AFNetworking', '~> 3.0.4'
pod 'Masonry', '~> 0.6.4'
pod 'SDWebImage', '~> 3.7.5'
pod 'JSONModel', '~> 1.2.0'
pod 'MJRefresh', '~> 3.1.12'
pod 'MBProgressHUD', '~> 1.0.0'
end

